# Generated by Django 5.1.6 on 2025-03-01 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_alter_book_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_view', 'can_view'), ('can_create', 'can_create'), ('can_edit', 'can_edit'), ('can_delete', 'can_delete')]},
        ),
    ]