# Generated by Django 5.1.6 on 2025-03-01 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0003_alter_book_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_view', 'can view'), ('can_create', 'can create'), ('can_edit', 'can edit'), ('can_delete', 'can delete')]},
        ),
    ]
    